version: "3.9"
services:
  app:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/inet-trouble-app
    networks:
      - inet-trouble-app

networks:
  inet-trouble-app:
    driver: bridge